apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec:
  project: default
  source:
    repoURL: https://github.com/Alkamist/digit-image-predictor-argocd
    targetRevision: {{ .Values.app.targetRevision }}
    path: kustomize/rabbitmq-cluster-operator 
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true