apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rabbitmq/cluster-operator.git
    targetRevision: v2.17.0
    path: ""
    kustomize:
      bases:
        - https://github.com/rabbitmq/cluster-operator/releases/download/v2.17.0/cluster-operator.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true